RockstarsHealthCheck/Controllers/QuestionaireController.cs
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using RockstarsHealthCheck.Models;

namespace RockstarsHealthCheck.Controllers
{
    public class QuestionaireController : Controller
    {
        private DataBase _dataBase = new DataBase();

        public IActionResult Index(int ID)
        {
            if (ID == 0)
            {
                ID = 2;
            }
            QuestionViewModel vm = new QuestionViewModel();
            vm.GetQuestions(ID);
            return View(vm);
        }

        [HttpGet("[action]")]
        public IActionResult End()
        {
            return View(new QuestionViewModel()) ;
        }

        [HttpPost("[action]")]
        public IActionResult End(QuestionViewModel viewModel)
        {
            _dataBase.SendAnswersToDataBase(viewModel);
            return View();
        }
    }
}

RockstarsHealthCheck/Views/Questionaire/End.cshtml
<link rel="stylesheet" href="~/css/Rockstyle.css" asp-append-version="true" />

<body onload="GetEndGif()">
    <div id="end_container">
        <H1> You Rock! </H1>
        <img name="gif">
    </div>
</body>

<script src="~/js/site.js"></script>

RockstarsHealthCheck/Views/Questionaire/Index.cshtml
@model QuestionViewModel
<link rel="stylesheet" href="~/css/Rockstyle.css" asp-append-version="true" />
<link rel="stylesheet" href="~/css/Slider.css" asp-append-version="true" />

<body class="questionnaireBody" onload="StartUp()">
    <form method="post" asp-controller="Questionaire" asp-action="End" id="myForm">
        <div class="slideshow-container">
            <div class="mySlides">
                <div class="question">
                    <label asp-for="Email">Please fill in your name and email</label>
                </div>
                <div class="NameInput">
                    <input class="emailInput" asp-for="Name" type="text" placeholder="Name" value="@Model.Name" />
                    <input class="emailInput" asp-for="Email" type="text" placeholder="Email" value="@Model.Email" />
                </div>
            </div>
            @for (int i = 0; i < Model.Questions.Count(); i++)
            {
                <div class="mySlides">
                    <div hidden="hidden">
                        <input asp-for="Questions[i].Id" value="@Model.Questions[i].Id" type="number" />
                        <input asp-for="Questions[i].Category" value="@Model.Questions[i].Category" type="text" />
                        <input asp-for="Questions[i].QuestionString" value="@Model.Questions[i].QuestionString" type="text" />
                        <input asp-for="Questions[i].Type" value="@Model.Questions[i].Type" type="text"/>
                    </div>

                    @if(Model.Questions[i].Type == "trend"){
                        <div class="question">
                            <label> @Model.Questions[i].QuestionString </label>
                        </div>
                        <div>
                            <div id="@(i+1)-div">
                                <input type="radio" id="@(i+1)-1" name="Questions[@i].Answer" value="-1" onclick="ChangeArrowColor('u')" />
                                <label for="@(i+1)-1" id="trendUp">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 330" style="enable-background:new 0 0 330 330;" xml:space="preserve" id="@(i+1)-TrendUp">
                                        <path id="XMLID_27_" d="M15,180h263.787l-49.394,49.394c-5.858,5.857-5.858,15.355,0,21.213C232.322,253.535,236.161,255,240,255s7.678-1.465,10.606-4.394l75-75c5.858-5.857,5.858-15.355,0-21.213l-75-75c-5.857-5.857-15.355-5.857-21.213,0c-5.858,5.857-5.858,15.355,0,21.213L278.787,150H15c-8.284,0-15,6.716-15,15S6.716,180,15,180z" />
                                    </svg>
                                </label>
                                <input type="radio" id="@(i+1)-2" name="Questions[@i].Answer" value="-2" onclick="ChangeArrowColor('e')" />
                                <label for="@(i+1)-2" id="trendEqual")>
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 330" style="enable-background:new 0 0 330 330;" xml:space="preserve" id="@(i+1)-TrendEqual">
                                        <path id="XMLID_27_" d="M15,180h263.787l-49.394,49.394c-5.858,5.857-5.858,15.355,0,21.213C232.322,253.535,236.161,255,240,255s7.678-1.465,10.606-4.394l75-75c5.858-5.857,5.858-15.355,0-21.213l-75-75c-5.857-5.857-15.355-5.857-21.213,0c-5.858,5.857-5.858,15.355,0,21.213L278.787,150H15c-8.284,0-15,6.716-15,15S6.716,180,15,180z" />
                                    </svg>
                                </label>
                                <input type="radio" id="@(i+1)-3" name="Questions[@i].Answer" value="-3" onclick="ChangeArrowColor('d')" />
                                <label for="@(i+1)-3" id="trendDown">
                                    <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 330 330" style="enable-background:new 0 0 330 330;" xml:space="preserve" id="@(i+1)-TrendDown">
                                        <path id="XMLID_27_" d="M15,180h263.787l-49.394,49.394c-5.858,5.857-5.858,15.355,0,21.213C232.322,253.535,236.161,255,240,255s7.678-1.465,10.606-4.394l75-75c5.858-5.857,5.858-15.355,0-21.213l-75-75c-5.857-5.857-15.355-5.857-21.213,0c-5.858,5.857-5.858,15.355,0,21.213L278.787,150H15c-8.284,0-15,6.716-15,15S6.716,180,15,180z" />
                                    </svg>
                                </label>
                            </div>
                        </div>  
                    } 
                    else 
                    {
                        <div class="question">
                            <label> @Model.Questions[i].QuestionString </label>
                        </div>
                        <div class="gifBody">
                            <img name="gif" id="@Model.Questions[i].Category">
                        </div>
                        <div id="@(i+1)-div">
                            <span class="star-group">
                                <input type="radio" id="@(i+1)-1" name="Questions[@i].Answer" value="1" onclick="ShowHideDiv()" /><label for="@(i+1)-1" id="star">☆</label>
                                <input type="radio" id="@(i+1)-2" name="Questions[@i].Answer" value="2" onclick="ShowHideDiv()" /><label for="@(i+1)-2" id="star">☆</label>
                                <input type="radio" id="@(i+1)-3" name="Questions[@i].Answer" value="3" onclick="ShowHideDiv()" /><label for="@(i+1)-3" id="star">☆</label>
                                <input type="radio" id="@(i+1)-4" name="Questions[@i].Answer" value="4" onclick="ShowHideDiv()" /><label for="@(i+1)-4" id="star">☆</label>
                                <input type="radio" id="@(i+1)-5" name="Questions[@i].Answer" value="5" onclick="ShowHideDiv()" /><label for="@(i+1)-5" id="star">☆</label>
                            </span>
                        </div>
                    }
                </div>

                <div class="mySlides">
                    <div class="question">
                        <label> @Model.Questions[i].QuestionString </label>
                    </div>
                    <div class="gifBody">
                        <img name="gif" id="@Model.Questions[i].Category">
                    </div>
                    <textarea asp-for="Questions[i].AnswerString" class="AnswerString" placeholder="But why?" rows="4">
                    </textarea>
                </div>
            }
            <div class="mySlides">
                <button type="submit" name="button" id="button2" class="btn btn-warning">Submit</button>
            </div>
            <div class="dotsDiv">
                @for(int j = 1; j<Model.Questions.Count()+1; j++){
                    <div class="dot" name="dot" id="@(j*2)"></div>
                }
            </div>
        </div>
    </form>
</body>
    
<script src="~/js/site.js"></script>

<script>
    document.getElementById("myForm").onkeypress = function(e) {
        var key = e.charCode || e.keyCode || 0;     
        if (key == 13) {
            if (slideIndex % 2 != 0) {
                let t = document.getElementsByClassName("emailInput");
                if (t[0].value != "" && t[1].value != ""){
                    plusSlides(1);
                }
            }
            e.preventDefault();
        }
    }

    document.addEventListener('touchstart', touchStart, false);
    document.addEventListener('touchend', touchEnd, false);
</script>